/**
 * Test stubs for #914 AC-2 and AC-5 — the shared `resolvePhasePolicies`
 * resolver (the "#833 firewall": one function both ExecutionConfig producers
 * call, so they cannot drift the way `config-resolver.ts` and
 * `ready-gate.ts` did in #833).
 *
 * Generated by /testgen from the /spec comment on #914. `parsePhaseSpec` and
 * `resolvePhasePolicies` do not exist yet — this file fails to import until
 * /exec adds and exports them from `config-resolver.ts`. That import failure
 * IS the stub: it turns green only once the real symbols exist.
 */

import { describe, it, expect } from "vitest";
import {
  parsePhaseSpec,
  resolvePhasePolicies,
  buildExecutionConfig,
  resolveRunOptions,
} from "./config-resolver.js";
import { DEFAULT_SETTINGS } from "../settings.js";
import type { SequantSettings } from "../settings.js";
import type { RunOptions } from "./types.js";

const PHASE_NAMES = ["spec", "exec", "qa", "test", "loop", "testgen"];

describe("#914 AC-2: parsePhaseSpec grammar", () => {
  it("applies a bare value to all phases", () => {
    // Given: "--models sonnet" (no phase= prefix)
    // When: parsed
    const result = parsePhaseSpec("sonnet", PHASE_NAMES);
    // Then: it applies to every phase via the "*" wildcard
    expect(result).toEqual({ "*": "sonnet" });
  });

  it("parses a comma list of phase=value pairs", () => {
    // Given: "--models spec=fable,exec=sonnet"
    const result = parsePhaseSpec("spec=fable,exec=sonnet", PHASE_NAMES);
    expect(result).toEqual({ spec: "fable", exec: "sonnet" });
  });

  it("throws on a malformed spec (empty value)", () => {
    // Given: "--models spec="
    expect(() => parsePhaseSpec("spec=", PHASE_NAMES)).toThrow();
  });

  it("throws on a mixed bare-and-pair spec", () => {
    // Given: "--models sonnet,exec=fable"
    expect(() => parsePhaseSpec("sonnet,exec=fable", PHASE_NAMES)).toThrow();
  });

  it("throws on an unknown phase name (CLI fail-fast, unlike settings' warn)", () => {
    // Given: "--models badphase=x"
    expect(() => parsePhaseSpec("badphase=x", PHASE_NAMES)).toThrow();
  });
});

describe("#914 AC-5: resolvePhasePolicies precedence (CLI > settings > absent)", () => {
  it("CLI overrides settings for the same phase", () => {
    // Given: CLI exec=sonnet, settings exec.model=opus
    const result = resolvePhasePolicies(
      "exec=sonnet",
      undefined,
      { exec: { model: "opus" } },
      PHASE_NAMES,
    );
    // Then: exec resolves to sonnet (CLI wins)
    expect(result.exec?.model).toBe("sonnet");
  });

  it("falls back to settings when no CLI override is given", () => {
    const result = resolvePhasePolicies(
      undefined,
      undefined,
      { exec: { model: "opus" } },
      PHASE_NAMES,
    );
    expect(result.exec?.model).toBe("opus");
  });

  it("resolves absent when neither CLI nor settings configure a phase", () => {
    const result = resolvePhasePolicies(undefined, undefined, {}, PHASE_NAMES);
    expect(result.exec).toBeUndefined();
  });
});

describe("#914 AC-5: buildExecutionConfig resolves phasePolicies (producer 1)", () => {
  function resolve(cli: Partial<RunOptions>, settings: SequantSettings) {
    return buildExecutionConfig(
      resolveRunOptions(cli as RunOptions, settings),
      settings,
      1,
    );
  }

  it("threads --models/--efforts CLI overrides into ExecutionConfig.phasePolicies", () => {
    // Given: CLI --models exec=sonnet --efforts exec=medium
    const cli: Partial<RunOptions> = {
      models: "exec=sonnet",
      efforts: "exec=medium",
    } as Partial<RunOptions>;

    // When: buildExecutionConfig resolves it
    const config = resolve(cli, DEFAULT_SETTINGS);

    // Then: phasePolicies.exec carries both
    expect(
      (config as unknown as { phasePolicies?: Record<string, unknown> })
        .phasePolicies?.exec,
    ).toEqual({ model: "sonnet", effort: "medium" });
  });

  it("with no per-phase config present, phasePolicies is absent or empty", () => {
    // AC-3's companion at the config layer: nothing configured -> nothing to
    // forward downstream.
    const config = resolve({}, DEFAULT_SETTINGS);
    const policies = (
      config as unknown as { phasePolicies?: Record<string, unknown> }
    ).phasePolicies;
    expect(policies == null || Object.keys(policies).length === 0).toBe(true);
  });
});

describe("#915 AC-1: buildExecutionConfig resolves effortEscalation (producer 1)", () => {
  function resolve(cli: Partial<RunOptions>, settings: SequantSettings) {
    return buildExecutionConfig(
      resolveRunOptions(cli as RunOptions, settings),
      settings,
      1,
    );
  }

  it("defaults to false when neither CLI nor settings opt in", () => {
    expect(resolve({}, DEFAULT_SETTINGS).effortEscalation).toBe(false);
  });

  it("settings.run.effortEscalation = true is honored with no CLI flag", () => {
    const settings: SequantSettings = {
      ...DEFAULT_SETTINGS,
      run: { ...DEFAULT_SETTINGS.run, effortEscalation: true },
    };
    expect(resolve({}, settings).effortEscalation).toBe(true);
  });

  it("--escalate-effort (CLI true) wins over settings.run.effortEscalation = false", () => {
    const settings: SequantSettings = {
      ...DEFAULT_SETTINGS,
      run: { ...DEFAULT_SETTINGS.run, effortEscalation: false },
    };
    const cli: Partial<RunOptions> = { escalateEffort: true };
    expect(resolve(cli, settings).effortEscalation).toBe(true);
  });
});
