import { describe, it, expect } from "vitest";
import { buildAutomatedPRBody, resolvePrLinkMode } from "./worktree-manager.js";

describe("buildAutomatedPRBody (#749)", () => {
  it("emits no QA note for READY_FOR_MERGE", () => {
    const body = buildAutomatedPRBody(42, { qaVerdict: "READY_FOR_MERGE" });
    expect(body).not.toContain("QA verdict");
    expect(body).toContain("Fixes #42");
    expect(body).toContain("Generated by `sequant run`");
  });

  it("emits no QA note when the verdict is absent", () => {
    const body = buildAutomatedPRBody(42);
    expect(body).not.toContain("QA verdict");
  });

  it("surfaces the AC_MET_BUT_NOT_A_PLUS note in the PR body", () => {
    const body = buildAutomatedPRBody(749, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
    });
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    expect(body).toContain("not A+");
    // The note precedes the trailer so it reads at the top of the body.
    expect(body.indexOf("QA verdict")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("surfaces the NEEDS_VERIFICATION note", () => {
    const body = buildAutomatedPRBody(1, { qaVerdict: "NEEDS_VERIFICATION" });
    expect(body).toContain("QA verdict: NEEDS_VERIFICATION");
    expect(body).toContain("external verification");
  });

  it("keeps the stack manifest (#605) alongside a verdict note", () => {
    const body = buildAutomatedPRBody(1, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      stackManifest: "### Stack\n- #1",
    });
    expect(body).toContain("### Stack");
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    // Manifest still sits before the trailer.
    expect(body.indexOf("### Stack")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });
});

describe("buildAutomatedPRBody — ready-gate report (#817)", () => {
  const report =
    "## sequant ready — Issue #817\n**✅ READY — awaiting human merge**";

  it("surfaces the ready-gate report in the PR body", () => {
    const body = buildAutomatedPRBody(817, { readyGateReport: report });
    expect(body).toContain("sequant ready — Issue #817");
    expect(body).toContain("awaiting human merge");
    // The report precedes the trailer so it reads at the top of the body.
    expect(body.indexOf("sequant ready")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("prefers the gate report over the standalone #749 note (no double headline)", () => {
    // The gate report already carries the terminal verdict, so the bare
    // AC_MET_BUT_NOT_A_PLUS note is suppressed to avoid a contradictory pair.
    const body = buildAutomatedPRBody(817, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      readyGateReport: report,
    });
    expect(body).toContain("sequant ready — Issue #817");
    expect(body).not.toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
  });

  it("keeps the stack manifest alongside the gate report", () => {
    const body = buildAutomatedPRBody(817, {
      readyGateReport: report,
      stackManifest: "### Stack\n- #817",
    });
    expect(body).toContain("### Stack");
    expect(body).toContain("sequant ready — Issue #817");
    expect(body.indexOf("### Stack")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });
});

describe("buildAutomatedPRBody — prIssueLink (#1197)", () => {
  it("AC-1: defaults to Fixes #N when linkMode is omitted", () => {
    const body = buildAutomatedPRBody(1197);
    expect(body).toContain("Fixes #1197");
    expect(body).not.toContain("Refs #1197");
  });

  it("AC-1: emits Fixes #N when linkMode is 'closes'", () => {
    const body = buildAutomatedPRBody(1197, { linkMode: "closes" });
    expect(body).toContain("Fixes #1197");
  });

  it("AC-1: emits Refs #N when linkMode is 'refs'", () => {
    const body = buildAutomatedPRBody(1197, { linkMode: "refs" });
    expect(body).toContain("Refs #1197");
    expect(body).not.toContain("Fixes #1197");
  });

  it("AC-4: rewrites an embedded closing verb for the same issue inside a table cell", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest:
        "| AC | Description |\n|----|----|\n| Fixes #1197 | full delivery |",
    });
    expect(body).not.toContain("Fixes #1197");
    expect(body).toContain("Refs #1197 | full delivery");
  });

  it("AC-4: leaves closing verbs for a different issue number untouched", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest: "Part of stack: Closes #1198",
    });
    expect(body).toContain("Closes #1198");
  });

  it("AC-4: is case-insensitive and covers close/fix/resolve verb families", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest: "resolved #1197 and CLOSE #1197",
    });
    expect(body).not.toMatch(/resolved #1197|CLOSE #1197/i);
    expect(body.match(/Refs #1197/g)?.length).toBeGreaterThanOrEqual(3);
  });
});

describe("resolvePrLinkMode (#1197)", () => {
  it("AC-1: defaults to 'closes' with no settings and no labels", () => {
    expect(resolvePrLinkMode(undefined, undefined, undefined)).toBe("closes");
  });

  it("AC-1: honors the settings value when no label is present", () => {
    expect(resolvePrLinkMode([], "refs", undefined)).toBe("refs");
    expect(resolvePrLinkMode(["enhancement"], "refs", undefined)).toBe("refs");
  });

  it("AC-2: the default 'no-autoclose' label forces 'refs' even when prIssueLink is 'closes'", () => {
    expect(resolvePrLinkMode(["no-autoclose"], "closes", undefined)).toBe(
      "refs",
    );
  });

  it("AC-2: a configured label name forces 'refs', not the default label string", () => {
    expect(resolvePrLinkMode(["tracker-only"], "closes", "tracker-only")).toBe(
      "refs",
    );
    // The default label name is inert once a custom one is configured.
    expect(resolvePrLinkMode(["no-autoclose"], "closes", "tracker-only")).toBe(
      "closes",
    );
  });
});
