import { describe, it, expect } from "vitest";
import { buildAutomatedPRBody } from "./worktree-manager.js";

describe("buildAutomatedPRBody (#749)", () => {
  it("emits no QA note for READY_FOR_MERGE", () => {
    const body = buildAutomatedPRBody(42, { qaVerdict: "READY_FOR_MERGE" });
    expect(body).not.toContain("QA verdict");
    expect(body).toContain("Fixes #42");
    expect(body).toContain("Generated by `sequant run`");
  });

  it("emits no QA note when the verdict is absent", () => {
    const body = buildAutomatedPRBody(42);
    expect(body).not.toContain("QA verdict");
  });

  it("surfaces the AC_MET_BUT_NOT_A_PLUS note in the PR body", () => {
    const body = buildAutomatedPRBody(749, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
    });
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    expect(body).toContain("not A+");
    // The note precedes the trailer so it reads at the top of the body.
    expect(body.indexOf("QA verdict")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("surfaces the NEEDS_VERIFICATION note", () => {
    const body = buildAutomatedPRBody(1, { qaVerdict: "NEEDS_VERIFICATION" });
    expect(body).toContain("QA verdict: NEEDS_VERIFICATION");
    expect(body).toContain("external verification");
  });

  it("keeps the stack manifest (#605) alongside a verdict note", () => {
    const body = buildAutomatedPRBody(1, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      stackManifest: "### Stack\n- #1",
    });
    expect(body).toContain("### Stack");
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    // Manifest still sits before the trailer.
    expect(body.indexOf("### Stack")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });
});
