import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  buildAutomatedPRBody,
  resolvePrLinkMode,
  extractExecSummary,
  sanitizeImportedClosingKeywords,
} from "./worktree-manager.js";
import type { GapFinding } from "./run-log-schema.js";

describe("buildAutomatedPRBody (#749)", () => {
  it("emits no QA note for READY_FOR_MERGE", () => {
    const body = buildAutomatedPRBody(42, { qaVerdict: "READY_FOR_MERGE" });
    expect(body).not.toContain("QA verdict");
    expect(body).toContain("Fixes #42");
    expect(body).toContain("Generated by `sequant run`");
  });

  it("emits no QA note when the verdict is absent", () => {
    const body = buildAutomatedPRBody(42);
    expect(body).not.toContain("QA verdict");
  });

  it("surfaces the AC_MET_BUT_NOT_A_PLUS note in the PR body", () => {
    const body = buildAutomatedPRBody(749, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
    });
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    expect(body).toContain("not A+");
    // The note precedes the trailer so it reads at the top of the body.
    expect(body.indexOf("QA verdict")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("surfaces the NEEDS_VERIFICATION note", () => {
    const body = buildAutomatedPRBody(1, { qaVerdict: "NEEDS_VERIFICATION" });
    expect(body).toContain("QA verdict: NEEDS_VERIFICATION");
    expect(body).toContain("external verification");
  });

  it("keeps the stack manifest (#605) alongside a verdict note", () => {
    const body = buildAutomatedPRBody(1, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      stackManifest: "### Stack\n- #1",
    });
    expect(body).toContain("### Stack");
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    // Manifest still sits before the trailer.
    expect(body.indexOf("### Stack")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });
});

describe("buildAutomatedPRBody — ready-gate report (#817)", () => {
  const report =
    "## sequant ready — Issue #817\n**✅ READY — awaiting human merge**";

  it("surfaces the ready-gate report in the PR body", () => {
    const body = buildAutomatedPRBody(817, { readyGateReport: report });
    expect(body).toContain("sequant ready — Issue #817");
    expect(body).toContain("awaiting human merge");
    // The report precedes the trailer so it reads at the top of the body.
    expect(body.indexOf("sequant ready")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("prefers the gate report over the standalone #749 note (no double headline)", () => {
    // The gate report already carries the terminal verdict, so the bare
    // AC_MET_BUT_NOT_A_PLUS note is suppressed to avoid a contradictory pair.
    const body = buildAutomatedPRBody(817, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      readyGateReport: report,
    });
    expect(body).toContain("sequant ready — Issue #817");
    expect(body).not.toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
  });

  it("keeps the stack manifest alongside the gate report", () => {
    const body = buildAutomatedPRBody(817, {
      readyGateReport: report,
      stackManifest: "### Stack\n- #817",
    });
    expect(body).toContain("### Stack");
    expect(body).toContain("sequant ready — Issue #817");
    expect(body.indexOf("### Stack")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });
});

describe("buildAutomatedPRBody — prIssueLink (#1197)", () => {
  it("AC-1: defaults to Fixes #N when linkMode is omitted", () => {
    const body = buildAutomatedPRBody(1197);
    expect(body).toContain("Fixes #1197");
    expect(body).not.toContain("Refs #1197");
  });

  it("AC-1: emits Fixes #N when linkMode is 'closes'", () => {
    const body = buildAutomatedPRBody(1197, { linkMode: "closes" });
    expect(body).toContain("Fixes #1197");
  });

  it("AC-1: emits Refs #N when linkMode is 'refs'", () => {
    const body = buildAutomatedPRBody(1197, { linkMode: "refs" });
    expect(body).toContain("Refs #1197");
    expect(body).not.toContain("Fixes #1197");
  });

  it("AC-4: rewrites an embedded closing verb for the same issue inside a table cell", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest:
        "| AC | Description |\n|----|----|\n| Fixes #1197 | full delivery |",
    });
    expect(body).not.toContain("Fixes #1197");
    expect(body).toContain("Refs #1197 | full delivery");
  });

  it("AC-4: leaves closing verbs for a different issue number untouched", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest: "Part of stack: Closes #1198",
    });
    expect(body).toContain("Closes #1198");
  });

  it("AC-4: is case-insensitive and covers close/fix/resolve verb families", () => {
    const body = buildAutomatedPRBody(1197, {
      linkMode: "refs",
      stackManifest: "resolved #1197 and CLOSE #1197",
    });
    expect(body).not.toMatch(/resolved #1197|CLOSE #1197/i);
    expect(body.match(/Refs #1197/g)?.length).toBeGreaterThanOrEqual(3);
  });
});

describe("resolvePrLinkMode (#1197)", () => {
  it("AC-1: defaults to 'closes' with no settings and no labels", () => {
    expect(resolvePrLinkMode(undefined, undefined, undefined)).toBe("closes");
  });

  it("AC-1: honors the settings value when no label is present", () => {
    expect(resolvePrLinkMode([], "refs", undefined)).toBe("refs");
    expect(resolvePrLinkMode(["enhancement"], "refs", undefined)).toBe("refs");
  });

  it("AC-2: the default 'no-autoclose' label forces 'refs' even when prIssueLink is 'closes'", () => {
    expect(resolvePrLinkMode(["no-autoclose"], "closes", undefined)).toBe(
      "refs",
    );
  });

  it("AC-2: a configured label name forces 'refs', not the default label string", () => {
    expect(resolvePrLinkMode(["tracker-only"], "closes", "tracker-only")).toBe(
      "refs",
    );
    // The default label name is inert once a custom one is configured.
    expect(resolvePrLinkMode(["no-autoclose"], "closes", "tracker-only")).toBe(
      "closes",
    );
  });
});

describe("extractExecSummary (#1223 AC-2)", () => {
  it("extracts the Summary section up to the next heading", () => {
    const output = [
      "## Plan",
      "Some plan text",
      "## Summary",
      "- Did thing A",
      "- Did thing B",
      "## Next Steps",
      "More stuff",
    ].join("\n");
    expect(extractExecSummary(output)).toBe("- Did thing A\n- Did thing B");
  });

  it("extracts the Summary section running to the end of the string", () => {
    const output = "## Summary\nOnly this remains.";
    expect(extractExecSummary(output)).toBe("Only this remains.");
  });

  it("uses the last Summary section when more than one is present", () => {
    const output = [
      "## Summary",
      "template example, not the real one",
      "## Summary",
      "the real summary",
    ].join("\n");
    expect(extractExecSummary(output)).toBe("the real summary");
  });

  it("returns undefined when no Summary section is present", () => {
    expect(extractExecSummary("## Plan\nNo summary here.")).toBeUndefined();
  });

  it("returns undefined for undefined input", () => {
    expect(extractExecSummary(undefined)).toBeUndefined();
  });

  // Real exec output (#1222's run, 2026-09-30) ends with `### Summary` after a
  // `### Pre-PR Confidence Check`. 4 of the 7 exec sessions that wrote a
  // summary that day used `###`, so an `##`-only match misses most of them.
  it("reads a real exec ending that uses ### Summary", () => {
    const output = readFileSync(
      join(__dirname, "__fixtures__/exec-output/1222-h3-summary.txt"),
      "utf-8",
    );
    const summary = extractExecSummary(output);

    expect(summary).toMatch(/^- \*\*AC-1\*\*/);
    expect(summary).toContain("All three ACs are mutation-verified");
    expect(summary).not.toContain("Pre-PR Confidence Check");
    expect(summary).not.toContain("Weakest part");
  });

  it("keeps a ## Summary's ### subsections and stops at the next ##", () => {
    const output = [
      "## Summary",
      "- Did A",
      "### Details",
      "- detail",
      "## Test plan",
      "- ran it",
    ].join("\n");
    expect(extractExecSummary(output)).toBe("- Did A\n### Details\n- detail");
  });

  it("stops a ### Summary at the next ### heading", () => {
    const output = "### Summary\n- Did A\n### Next steps\n- later";
    expect(extractExecSummary(output)).toBe("- Did A");
  });

  it("returns undefined for an empty Summary section", () => {
    const output = "## Summary\n\n## Next";
    expect(extractExecSummary(output)).toBeUndefined();
  });

  it("caps a runaway summary to ~4KB", () => {
    const huge = "x".repeat(5000);
    const output = `## Summary\n${huge}`;
    const result = extractExecSummary(output);
    expect(result?.length).toBe(4000);
  });
});

describe("sanitizeImportedClosingKeywords (#1223 AC-3)", () => {
  it("rewrites Closes #N to Refs #N", () => {
    expect(sanitizeImportedClosingKeywords("Closes #279")).toBe("Refs #279");
  });

  it("rewrites cross-repo and URL references, which close other repos' issues too", () => {
    expect(sanitizeImportedClosingKeywords("Fixes owner/repo#12")).toBe(
      "Refs owner/repo#12",
    );
    expect(
      sanitizeImportedClosingKeywords(
        "Resolves https://github.com/owner/repo/issues/12",
      ),
    ).toBe("Refs https://github.com/owner/repo/issues/12");
  });

  it("rewrites fixes #N (lowercase) to Refs #N", () => {
    expect(sanitizeImportedClosingKeywords("fixes #1223")).toBe("Refs #1223");
  });

  it("rewrites resolve #N to Refs #N", () => {
    expect(sanitizeImportedClosingKeywords("resolve #10")).toBe("Refs #10");
  });

  it("leaves text without closing keywords untouched", () => {
    expect(sanitizeImportedClosingKeywords("See #279 for context")).toBe(
      "See #279 for context",
    );
  });
});

describe("buildAutomatedPRBody — exec summary import (#1223 AC-2, AC-3)", () => {
  it("uses exec's Summary section in place of the placeholder", () => {
    const execOutput = "## Summary\n- Implemented the thing\n## Next";
    const body = buildAutomatedPRBody(1223, { execOutput });
    expect(body).toContain("- Implemented the thing");
    expect(body).not.toContain("Automated PR for issue #1223.");
  });

  it("falls back to the placeholder when exec output has no Summary", () => {
    const body = buildAutomatedPRBody(1223, {
      execOutput: "## Plan\nNo summary",
    });
    expect(body).toContain("Automated PR for issue #1223.");
  });

  it("falls back to the placeholder when execOutput is absent", () => {
    const body = buildAutomatedPRBody(1223);
    expect(body).toContain("Automated PR for issue #1223.");
  });

  it("rewrites a Closes reference to an unrelated issue inside the imported summary", () => {
    const execOutput =
      "## Summary\nClose #279 with the AC mapping comment after this merges.";
    const body = buildAutomatedPRBody(1223, { execOutput });
    expect(body).toContain("Refs #279");
    expect(body).not.toMatch(/\bClose[sd]?\s+#279/i);
  });

  it("rewrites a closing reference to the PR's own issue inside the imported summary, while the trailer still closes it", () => {
    const execOutput = "## Summary\nfixes #1223 in this change.";
    const body = buildAutomatedPRBody(1223, { execOutput });
    // Imported text sanitized...
    expect(body).toContain("Refs #1223 in this change");
    // ...but the body's own trailer still carries the real close.
    expect(body).toContain("Fixes #1223");
  });

  it("sanitizes the imported summary even under linkMode 'refs'", () => {
    const execOutput = "## Summary\nCloses #279 too.";
    const body = buildAutomatedPRBody(1223, {
      execOutput,
      linkMode: "refs",
    });
    expect(body).toContain("Refs #279");
  });
});

describe("buildAutomatedPRBody — follow-ups (#1249)", () => {
  const finding = (
    description: string,
    recommendedAction: GapFinding["recommendedAction"] = "document",
  ): GapFinding => ({
    category: "risk_gap",
    evidence: "src/x.ts:1",
    description,
    recommendedAction,
  });

  it("renders one checklist line per document finding with its resolution", () => {
    const body = buildAutomatedPRBody(1249, {
      followups: [
        finding(
          "Sibling writer in src/a.ts shares the root cause — filed #1300",
        ),
        finding("Tighten the log message — fixed in this PR"),
        finding("Port to Windows — dropped: no Windows users"),
        finding("Adjacent unguarded writeFile sites"),
      ],
    });
    const section = body.slice(body.indexOf("## Follow-ups"));
    expect(section).toContain(
      "- [x] Sibling writer in src/a.ts shares the root cause — filed #1300",
    );
    expect(section).toContain(
      "- [x] Tighten the log message — fixed in this PR",
    );
    expect(section).toContain(
      "- [x] Port to Windows — dropped: no Windows users",
    );
    expect(section).toContain(
      "- [ ] Adjacent unguarded writeFile sites — unresolved",
    );
    // The checklist sits before the trailer.
    expect(body.indexOf("## Follow-ups")).toBeLessThan(
      body.indexOf("Generated by `sequant run`"),
    );
  });

  it("does not double an unresolved suffix QA already wrote", () => {
    const body = buildAutomatedPRBody(1249, {
      followups: [
        finding("Adjacent unguarded writeFile sites — ⚠️ unresolved"),
      ],
    });
    expect(body).toContain(
      "- [ ] Adjacent unguarded writeFile sites — unresolved",
    );
    expect(body).not.toMatch(/unresolved — unresolved/);
  });

  it("renders no section when there are no findings", () => {
    expect(buildAutomatedPRBody(1249)).not.toContain("## Follow-ups");
    expect(buildAutomatedPRBody(1249, { followups: [] })).not.toContain(
      "## Follow-ups",
    );
  });

  it("excludes fix_now and pause_for_human findings", () => {
    const body = buildAutomatedPRBody(1249, {
      followups: [
        finding("AC-3 not implemented", "fix_now"),
        finding("Needs an owner decision", "pause_for_human"),
      ],
    });
    expect(body).not.toContain("## Follow-ups");
    expect(body).not.toContain("AC-3 not implemented");
  });

  it("neutralizes a closing keyword inside a finding", () => {
    const body = buildAutomatedPRBody(1249, {
      followups: [finding("This also fixes #812 in passing")],
    });
    expect(body).toContain("Refs #812");
    expect(body).not.toMatch(/fixes #812/i);
  });

  it("renders after the QA note and before the stack manifest", () => {
    const body = buildAutomatedPRBody(1249, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      stackManifest: "## Stack\n\n- #1",
      followups: [finding("Something deferred")],
    });
    const note = body.indexOf("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    const followups = body.indexOf("## Follow-ups");
    expect(note).toBeGreaterThan(-1);
    expect(followups).toBeGreaterThan(note);
    expect(body.indexOf("## Stack")).toBeGreaterThan(followups);
  });
});

describe("buildAutomatedPRBody — QA has not run (#1246)", () => {
  it("AC-1: renders one line naming the phases that ran", () => {
    const body = buildAutomatedPRBody(1246, {
      qaNotRun: { phasesRun: ["spec", "exec"] },
    });
    const lines = body.split("\n").filter((l) => l.includes("QA has not run"));
    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatch(
      /^> \*\*QA has not run\*\* — phases run: spec, exec\./,
    );
    expect(lines[0]).toContain("sequant run 1246 --phases qa");
    // The line sits above the trailer, in the verdict-note slot.
    expect(body.indexOf("QA has not run")).toBeLessThan(
      body.indexOf("Generated by"),
    );
  });

  it("AC-2: a verdict note wins — never both in one body", () => {
    const body = buildAutomatedPRBody(1246, {
      qaVerdict: "AC_MET_BUT_NOT_A_PLUS",
      qaNotRun: { phasesRun: ["exec"] },
    });
    expect(body).toContain("QA verdict: AC_MET_BUT_NOT_A_PLUS");
    expect(body).not.toContain("QA has not run");
  });

  it("AC-2: READY_FOR_MERGE (no verdict note) still drops the line", () => {
    const body = buildAutomatedPRBody(1246, {
      qaVerdict: "READY_FOR_MERGE",
      qaNotRun: { phasesRun: ["exec"] },
    });
    expect(body).not.toContain("QA has not run");
  });

  it("AC-2: a ready-gate report replaces the line", () => {
    const body = buildAutomatedPRBody(1246, {
      readyGateReport: "## sequant ready — Issue #1246",
      qaNotRun: { phasesRun: ["exec"] },
    });
    expect(body).not.toContain("QA has not run");
  });

  it("AC-3: without qaNotRun the body is unchanged", () => {
    expect(buildAutomatedPRBody(1246, { qaNotRun: undefined })).toBe(
      buildAutomatedPRBody(1246),
    );
    expect(buildAutomatedPRBody(1246)).not.toContain("QA has not run");
  });
});
