/**
 * Assess Comment Parser
 *
 * Detects and parses /assess command output from GitHub issue comments.
 * This is the unified parser that handles both the new /assess format
 * and the legacy /solve format for backward compatibility.
 *
 * When an assess comment exists, its phase recommendations take precedence
 * over content analysis (but not over labels).
 *
 * @example
 * ```typescript
 * import { findAssessComment, parseAssessWorkflow } from './assess-comment-parser';
 *
 * const comments = [
 *   { body: "Some regular comment" },
 *   { body: "## Assess Analysis\n\n→ PROCEED — Ready.\n\n<!-- assess:phases=spec,exec,qa -->" },
 * ];
 *
 * const assessComment = findAssessComment(comments);
 * if (assessComment) {
 *   const workflow = parseAssessWorkflow(assessComment.body);
 *   // workflow: { phases: ['spec', 'exec', 'qa'], action: 'PROCEED', ... }
 * }
 * ```
 */

import type { Phase } from "./workflow/types.js";
import type { PhaseSignal } from "./phase-signal.js";

/**
 * The 6 fixed actions that /assess can recommend
 */
export type AssessAction =
  | "PROCEED"
  | "CLOSE"
  | "MERGE"
  | "REWRITE"
  | "CLARIFY"
  | "PARK";

/**
 * Result of parsing an assess comment (superset of SolveWorkflowResult)
 */
export interface AssessWorkflowResult {
  /** Phases recommended by assess (only meaningful for PROCEED) */
  phases: Phase[];
  /** Whether quality loop is recommended */
  qualityLoop: boolean;
  /** The issue numbers mentioned in the assess comment */
  issueNumbers: number[];
  /** Raw workflow string (e.g., "spec → exec → qa") */
  workflowString?: string;
  /** The recommended action (one of the 6 fixed actions) */
  action?: AssessAction;
}

/**
 * Backward-compatible alias for AssessWorkflowResult
 */
export type SolveWorkflowResult = AssessWorkflowResult;

/**
 * Comment structure (simplified from GitHub API)
 */
export interface IssueComment {
  body: string;
  author?: {
    login: string;
  };
  createdAt?: string;
}

/**
 * Markers that indicate an assess comment (new format)
 */
const ASSESS_MARKERS = [
  "## Assess Analysis",
  "## Assess Workflow",
  "*Generated by `/assess",
];

/**
 * Markers that indicate a solve comment (legacy format)
 */
const SOLVE_MARKERS = [
  "## Solve Analysis",
  "## Solve Workflow for Issues:",
  "## Solve Workflow for Issue:",
  "### Recommended Workflow",
  "*📝 Generated by `/solve",
];

/**
 * All markers (both assess and solve)
 */
const ALL_MARKERS = [...ASSESS_MARKERS, ...SOLVE_MARKERS];

/**
 * Pattern to extract phases from workflow string
 * Matches: `/spec`, `/exec`, `/test`, `/qa`, etc.
 * Also matches without slash: `spec`, `exec`, `test`, `qa` (for arrow notation)
 */
const PHASE_PATTERN =
  /\/?(?<!\w)(spec|exec|test|qa|security-review|testgen|loop)(?!\w)/g;

/**
 * Pattern to detect quality loop recommendation
 */
const QUALITY_LOOP_PATTERNS = [
  /quality\s*loop.*auto-enable/i,
  /--quality-loop/i,
  /quality\s*loop.*recommended/i,
  /enable.*quality\s*loop/i,
];

/**
 * Pattern to extract structured data from HTML comment markers
 * Matches both: <!-- assess:phases=exec,qa --> and <!-- solve:phases=exec,qa -->
 */
const HTML_MARKER_PATTERN =
  /<!--\s*(?:assess|solve):(\w[\w-]*)=([\w,.-]*)\s*-->/g;

/**
 * Pattern to extract assess-specific HTML markers (takes precedence)
 */
const ASSESS_HTML_MARKER_PATTERN = /<!--\s*assess:(\w[\w-]*)=([\w,.-]*)\s*-->/g;

/**
 * Non-global pattern for `.test()` checks. Matches any assess/solve action
 * marker — the durable contract written by /assess regardless of prose format.
 */
const ASSESS_ACTION_MARKER_PATTERN =
  /<!--\s*(?:assess|solve):action=[\w-]+\s*-->/;

/**
 * Pattern to extract issue numbers from header
 * Matches: "## Solve Workflow for Issues: 123, 456" or "#123"
 */
const ISSUE_NUMBER_PATTERN = /#?(\d+)/g;

/**
 * Valid assess actions
 */
const VALID_ACTIONS: AssessAction[] = [
  "PROCEED",
  "CLOSE",
  "MERGE",
  "REWRITE",
  "CLARIFY",
  "PARK",
];

/**
 * Structured data extracted from HTML comment markers
 */
export interface AssessMarkers {
  /** Recommended phases */
  phases?: string[];
  /** Whether quality loop is recommended */
  qualityLoop?: boolean;
  /** The recommended action */
  action?: AssessAction;
}

/**
 * Backward-compatible alias for AssessMarkers
 */
export type SolveMarkers = AssessMarkers;

// ─── Detection Functions ────────────────────────────────────────────────────

/**
 * Check if a comment is an assess command output (new format).
 *
 * Matches either prose markers (e.g., "## Assess Analysis") or the durable
 * HTML action marker `<!-- assess:action=... -->` written by every /assess
 * comment regardless of prose format. The HTML marker is the contract;
 * prose can change.
 */
export function isAssessComment(body: string): boolean {
  if (ALL_MARKERS.some((marker) => body.includes(marker))) return true;
  return ASSESS_ACTION_MARKER_PATTERN.test(body);
}

/**
 * Check if a comment is a solve command output (legacy format)
 * @deprecated Use isAssessComment instead
 */
export function isSolveComment(body: string): boolean {
  return isAssessComment(body);
}

/**
 * Find the most recent assess/solve comment from a list of comments
 */
export function findAssessComment(
  comments: IssueComment[],
): IssueComment | null {
  for (let i = comments.length - 1; i >= 0; i--) {
    if (isAssessComment(comments[i].body)) {
      return comments[i];
    }
  }
  return null;
}

/**
 * Find every assess/solve comment in chronological order (oldest first).
 *
 * Preserves the input order of `comments`, which is the order GitHub returns
 * them (chronological). Callers that need the most recent comment should
 * read the last element.
 */
export function findAllAssessComments(
  comments: IssueComment[],
): IssueComment[] {
  return comments.filter((c) => isAssessComment(c.body));
}

/**
 * Find the most recent solve comment from a list of comments
 * @deprecated Use findAssessComment instead
 */
export function findSolveComment(
  comments: IssueComment[],
): IssueComment | null {
  return findAssessComment(comments);
}

// ─── Parsing Functions ──────────────────────────────────────────────────────

/**
 * Parse phases from a workflow string
 */
function parseWorkflowString(workflowString: string): Phase[] {
  const phases: Phase[] = [];
  const matches = workflowString.matchAll(PHASE_PATTERN);

  for (const match of matches) {
    const phase = match[1] as Phase;
    if (!phases.includes(phase)) {
      phases.push(phase);
    }
  }

  return phases;
}

/**
 * Parse HTML comment markers from a comment body
 *
 * Supports both `assess:` and `solve:` prefixes.
 * When both are present, `assess:` markers take precedence.
 */
export function parseAssessMarkers(body: string): AssessMarkers {
  const markers: AssessMarkers = {};

  // First pass: collect all markers (both assess: and solve:)
  const allMatches = body.matchAll(HTML_MARKER_PATTERN);
  for (const match of allMatches) {
    applyMarker(markers, match[1], match[2]);
  }

  // Second pass: assess: markers override solve: markers
  const assessMatches = body.matchAll(ASSESS_HTML_MARKER_PATTERN);
  for (const match of assessMatches) {
    applyMarker(markers, match[1], match[2]);
  }

  return markers;
}

/**
 * Apply a single marker key-value pair to the markers object
 */
function applyMarker(markers: AssessMarkers, key: string, value: string): void {
  switch (key) {
    case "phases":
      markers.phases = value.split(",").filter(Boolean);
      break;
    case "quality-loop":
      markers.qualityLoop = value === "true";
      break;
    case "action":
      if (VALID_ACTIONS.includes(value as AssessAction)) {
        markers.action = value as AssessAction;
      }
      break;
  }
}

/**
 * Parse HTML comment markers (backward-compatible alias)
 * @deprecated Use parseAssessMarkers instead
 */
export function parseSolveMarkers(body: string): AssessMarkers {
  return parseAssessMarkers(body);
}

/**
 * Parse an assess/solve comment to extract workflow information
 */
export function parseAssessWorkflow(body: string): AssessWorkflowResult {
  const result: AssessWorkflowResult = {
    phases: [],
    qualityLoop: false,
    issueNumbers: [],
  };

  // Extract action from "→ ACTION — reason" line
  const actionMatch = body.match(
    /→\s*(PROCEED|CLOSE|MERGE|REWRITE|CLARIFY|PARK)\s*[—-]/,
  );
  if (actionMatch) {
    result.action = actionMatch[1] as AssessAction;
  }

  // Extract issue numbers from header (both old and new formats)
  const headerMatch = body.match(
    /## (?:Assess|Solve) (?:Workflow for Issues?|Analysis)(?::\s*|\s+for\s+)([^\n]+)/i,
  );
  if (headerMatch) {
    const numberMatches = headerMatch[1].matchAll(ISSUE_NUMBER_PATTERN);
    for (const match of numberMatches) {
      const num = parseInt(match[1], 10);
      if (!isNaN(num) && !result.issueNumbers.includes(num)) {
        result.issueNumbers.push(num);
      }
    }
  }

  // Try HTML comment markers first (most reliable, machine-readable)
  const markers = parseAssessMarkers(body);

  // Action from markers overrides inline detection
  if (markers.action) {
    result.action = markers.action;
  }

  if (markers.phases && markers.phases.length > 0) {
    result.phases = markers.phases as Phase[];
    result.workflowString = markers.phases.join(" → ");
  }

  if (markers.qualityLoop !== undefined) {
    result.qualityLoop = markers.qualityLoop;
  }

  // If we got phases from markers, we're done with phase detection
  if (result.phases.length > 0) {
    return result;
  }

  // Find workflow lines (e.g., "/spec 152" or "spec → exec → qa")
  const lines = body.split("\n");

  // First pass: look for arrow notation (most reliable)
  for (const line of lines) {
    if (line.includes("→") || line.includes("->")) {
      const phases = parseWorkflowString(line);
      if (phases.length > 0) {
        result.phases = phases;
        result.workflowString = line.trim();
        break;
      }
    }
  }

  // Second pass: if no arrow notation found, collect phases from multiple lines
  if (result.phases.length === 0) {
    const collectedPhases: Phase[] = [];

    for (const line of lines) {
      if (
        line.includes("/spec") ||
        line.includes("/exec") ||
        line.includes("/test") ||
        line.includes("/qa")
      ) {
        const linePhases = parseWorkflowString(line);
        for (const phase of linePhases) {
          if (!collectedPhases.includes(phase)) {
            collectedPhases.push(phase);
          }
        }
      }
    }

    if (collectedPhases.length > 0) {
      result.phases = collectedPhases;
      result.workflowString = collectedPhases.map((p) => `/${p}`).join(" → ");
    }
  }

  // If no phases found from lines, try full body
  if (result.phases.length === 0) {
    result.phases = parseWorkflowString(body);
  }

  // Check for quality loop recommendation (if not already set by markers)
  if (!result.qualityLoop) {
    for (const pattern of QUALITY_LOOP_PATTERNS) {
      if (pattern.test(body)) {
        result.qualityLoop = true;
        break;
      }
    }
  }

  return result;
}

/**
 * Parse a solve comment to extract workflow information
 * @deprecated Use parseAssessWorkflow instead
 */
export function parseSolveWorkflow(body: string): AssessWorkflowResult {
  return parseAssessWorkflow(body);
}

// ─── Signal Conversion ──────────────────────────────────────────────────────

/**
 * Convert assess workflow result to phase signals
 */
export function assessWorkflowToSignals(
  workflow: AssessWorkflowResult,
): PhaseSignal[] {
  const signals: PhaseSignal[] = [];

  for (const phase of workflow.phases) {
    signals.push({
      phase,
      source: "assess",
      confidence: "high",
      reason: `Recommended by /assess command: ${workflow.workflowString || phase}`,
    });
  }

  if (workflow.qualityLoop) {
    signals.push({
      phase: "quality-loop",
      source: "assess",
      confidence: "high",
      reason: "Quality loop recommended by /assess command",
    });
  }

  return signals;
}

/**
 * Convert solve workflow result to phase signals
 *
 * Preserves "/solve" wording in reason strings for backward compatibility
 * with existing tests and consumers.
 *
 * @deprecated Use assessWorkflowToSignals instead
 */
export function solveWorkflowToSignals(
  workflow: AssessWorkflowResult,
): PhaseSignal[] {
  const signals: PhaseSignal[] = [];

  for (const phase of workflow.phases) {
    signals.push({
      phase,
      source: "solve",
      confidence: "high",
      reason: `Recommended by /solve command: ${workflow.workflowString || phase}`,
    });
  }

  if (workflow.qualityLoop) {
    signals.push({
      phase: "quality-loop",
      source: "solve",
      confidence: "high",
      reason: "Quality loop recommended by /solve command",
    });
  }

  return signals;
}

// ─── Utility Functions ──────────────────────────────────────────────────────

/**
 * Check if assess/solve comment covers the current issue
 */
export function assessCoversIssue(
  workflow: AssessWorkflowResult,
  issueNumber: number,
): boolean {
  return workflow.issueNumbers.includes(issueNumber);
}

/**
 * Check if solve comment covers the current issue
 * @deprecated Use assessCoversIssue instead
 */
export function solveCoversIssue(
  workflow: AssessWorkflowResult,
  issueNumber: number,
): boolean {
  return assessCoversIssue(workflow, issueNumber);
}

// ─── Prior-Assessment Detection ─────────────────────────────────────────────

/**
 * Pattern matching exec phase markers in any comment.
 * Used by detectChurn to differentiate "no execution" churn from
 * legitimate re-assessment after exec.
 */
const EXEC_PHASE_MARKER_PATTERN =
  /<!--\s*SEQUANT_PHASE:\s*\{[^}]*"phase"\s*:\s*"exec"[^}]*\}\s*-->/;

/**
 * Format a comment's createdAt timestamp as YYYY-MM-DD.
 * Falls back to the raw value when missing or unparseable so output
 * still says something useful.
 */
function formatAssessDate(createdAt?: string): string {
  if (!createdAt) return "unknown date";
  const parsed = new Date(createdAt);
  if (isNaN(parsed.getTime())) return createdAt;
  return parsed.toISOString().slice(0, 10);
}

/**
 * Build a one-line supersession header for a new assess comment.
 *
 * Format:
 * - 0 priors → null (caller omits the header entirely)
 * - 1 prior  → `Supersedes prior assess from <date> (<action>)`
 * - ≥2 priors → `Supersedes N prior assessments (most recent: <date>)`
 *
 * Priors must be passed in chronological order (oldest first), matching
 * the output of findAllAssessComments.
 */
export function buildSupersessionHeader(priors: IssueComment[]): string | null {
  if (priors.length === 0) return null;

  const mostRecent = priors[priors.length - 1];
  const date = formatAssessDate(mostRecent.createdAt);

  if (priors.length === 1) {
    const workflow = parseAssessWorkflow(mostRecent.body);
    const action = workflow.action ?? "unknown";
    return `Supersedes prior assess from ${date} (${action})`;
  }

  return `Supersedes ${priors.length} prior assessments (most recent: ${date})`;
}

/**
 * Result of churn detection: whether to fire the warning, the count
 * of prior assessments, and the date of the first one.
 */
export interface ChurnResult {
  isChurn: boolean;
  count: number;
  firstDate?: string;
}

/**
 * Detect re-assessment churn — repeated /assess invocations without
 * an intervening exec phase. Fires only when ≥3 priors exist and no
 * exec phase marker appears in any comment dated after the first prior.
 *
 * `allComments` should be the full comment list from the issue
 * (including the prior assess comments themselves) so we can search
 * for SEQUANT_PHASE exec markers in non-assess comments.
 */
export function detectChurn(
  priors: IssueComment[],
  allComments: IssueComment[],
): ChurnResult {
  const count = priors.length;
  if (count < 3) {
    return { isChurn: false, count };
  }

  const firstPrior = priors[0];
  const firstDate = formatAssessDate(firstPrior.createdAt);
  const firstTimestamp = firstPrior.createdAt
    ? new Date(firstPrior.createdAt).getTime()
    : NaN;

  const hasExecAfterFirst = allComments.some((c) => {
    if (!EXEC_PHASE_MARKER_PATTERN.test(c.body)) return false;
    if (!Number.isFinite(firstTimestamp)) return true;
    if (!c.createdAt) return true;
    const ts = new Date(c.createdAt).getTime();
    if (isNaN(ts)) return true;
    return ts >= firstTimestamp;
  });

  return {
    isChurn: !hasExecAfterFirst,
    count,
    firstDate,
  };
}

/**
 * Decide whether to prompt the user before posting a new assess comment
 * that conflicts with the most recent prior recommendation.
 *
 * Prompts only when:
 *   - A prior action exists, AND
 *   - The prior action is PROCEED or REWRITE (the "do work" actions
 *     where flipping to PARK/CLOSE/etc. needs explicit confirmation), AND
 *   - The new action differs from the prior.
 *
 * Skips the prompt for prior CLOSE/PARK/CLARIFY/MERGE — flipping
 * away from those is rarely "wrong" and the prompt would just be noise.
 */
export function shouldPromptOnConflict(
  priorAction: AssessAction | undefined,
  newAction: AssessAction | undefined,
): boolean {
  if (!priorAction || !newAction) return false;
  if (priorAction === newAction) return false;
  return priorAction === "PROCEED" || priorAction === "REWRITE";
}
