// Tests for unified assess/solve comment parser
// Run with: npm test -- src/lib/assess-comment-parser.test.ts

import { describe, it, expect } from "vitest";

import {
  isAssessComment,
  findAssessComment,
  parseAssessMarkers,
  parseAssessWorkflow,
  assessWorkflowToSignals,
  assessCoversIssue,
  // Backward-compat re-exports
  isSolveComment,
  findSolveComment,
  parseSolveMarkers,
  parseSolveWorkflow,
  solveWorkflowToSignals,
  solveCoversIssue,
} from "./assess-comment-parser.js";
import type {
  AssessWorkflowResult,
  AssessAction,
  IssueComment,
  SolveWorkflowResult,
  SolveMarkers,
} from "./assess-comment-parser.js";

// === AC-7: solve-comment-parser updated for assess format ===
// === AC-14: Unit tests for assess marker parsing ===

describe("assess-comment-parser", () => {
  describe("AC-7: assess marker detection", () => {
    describe("isAssessComment", () => {
      it("should detect ## Assess Analysis marker", () => {
        const body = `## Assess Analysis\n\n→ PROCEED — Issue is clear.\n\n<!-- assess:phases=spec,exec,qa -->`;
        expect(isAssessComment(body)).toBe(true);
      });

      it("should detect ## Assess Workflow marker", () => {
        const body = `## Assess Workflow\n\nspec → exec → qa`;
        expect(isAssessComment(body)).toBe(true);
      });

      it("should detect *Generated by \`/assess\` marker", () => {
        const body = `Some content\n\n*Generated by \`/assess\`*`;
        expect(isAssessComment(body)).toBe(true);
      });

      it("should still detect legacy solve markers", () => {
        const body = `## Solve Workflow for Issues: 123\nspec → exec → qa`;
        expect(isAssessComment(body)).toBe(true);
      });

      it("should detect ## Solve Analysis marker", () => {
        const body = `## Solve Analysis\n\n**Recommended Phases:** spec → exec → qa`;
        expect(isAssessComment(body)).toBe(true);
      });

      it("should return false for regular comments", () => {
        expect(isAssessComment("Just a regular comment")).toBe(false);
        expect(isAssessComment("")).toBe(false);
        expect(isAssessComment("## Some Other Header")).toBe(false);
      });
    });

    describe("findAssessComment", () => {
      it("should find most recent assess comment", () => {
        const comments: IssueComment[] = [
          { body: "Regular comment" },
          { body: "## Assess Analysis\n\n→ PROCEED — First assess." },
          { body: "Another regular comment" },
          { body: "## Assess Analysis\n\n→ CLOSE — Second assess." },
        ];
        const result = findAssessComment(comments);
        expect(result).not.toBeNull();
        expect(result!.body).toContain("Second assess");
      });

      it("should prefer most recent comment regardless of format", () => {
        const comments: IssueComment[] = [
          { body: "## Solve Workflow for Issues: 123\nspec → exec → qa" },
          { body: "## Assess Analysis\n\n→ PROCEED — Newer assess." },
        ];
        const result = findAssessComment(comments);
        expect(result!.body).toContain("Newer assess");
      });

      it("should return null when no assess/solve comments exist", () => {
        const comments: IssueComment[] = [
          { body: "Regular comment" },
          { body: "Another regular comment" },
        ];
        expect(findAssessComment(comments)).toBeNull();
      });

      it("should return null for empty array", () => {
        expect(findAssessComment([])).toBeNull();
      });
    });
  });

  describe("AC-14: assess marker parsing", () => {
    describe("parseAssessMarkers", () => {
      it("should parse <!-- assess:phases=... --> marker", () => {
        const body = "Some content\n<!-- assess:phases=spec,exec,qa -->";
        const markers = parseAssessMarkers(body);
        expect(markers.phases).toEqual(["spec", "exec", "qa"]);
      });

      it("should parse <!-- assess:action=PROCEED --> marker", () => {
        const body = "<!-- assess:action=PROCEED -->";
        const markers = parseAssessMarkers(body);
        expect(markers.action).toBe("PROCEED");
      });

      it("should parse all 6 action types", () => {
        const actions: AssessAction[] = [
          "PROCEED",
          "CLOSE",
          "MERGE",
          "REWRITE",
          "CLARIFY",
          "PARK",
        ];
        for (const action of actions) {
          const markers = parseAssessMarkers(
            `<!-- assess:action=${action} -->`,
          );
          expect(markers.action).toBe(action);
        }
      });

      it("should parse <!-- assess:quality-loop=true --> marker", () => {
        const body = "<!-- assess:quality-loop=true -->";
        const markers = parseAssessMarkers(body);
        expect(markers.qualityLoop).toBe(true);
      });

      it("should parse <!-- assess:quality-loop=false --> marker", () => {
        const body = "<!-- assess:quality-loop=false -->";
        const markers = parseAssessMarkers(body);
        expect(markers.qualityLoop).toBe(false);
      });

      it("should parse <!-- assess:skip-spec=true --> marker", () => {
        const body = "<!-- assess:skip-spec=true -->";
        const markers = parseAssessMarkers(body);
        expect(markers.skipSpec).toBe(true);
      });

      it("should parse <!-- assess:browser-test=true --> marker", () => {
        const body = "<!-- assess:browser-test=true -->";
        const markers = parseAssessMarkers(body);
        expect(markers.browserTest).toBe(true);
      });

      it("should still parse legacy <!-- solve:phases=... --> markers", () => {
        const body = "<!-- solve:phases=exec,qa -->";
        const markers = parseAssessMarkers(body);
        expect(markers.phases).toEqual(["exec", "qa"]);
      });

      it("should prefer assess markers over solve markers when both present", () => {
        const body =
          "<!-- solve:phases=spec,exec -->\n<!-- assess:phases=exec,qa -->";
        const markers = parseAssessMarkers(body);
        expect(markers.phases).toEqual(["exec", "qa"]);
      });

      it("should parse multiple markers from same comment", () => {
        const body = [
          "<!-- assess:phases=spec,exec,qa -->",
          "<!-- assess:action=PROCEED -->",
          "<!-- assess:quality-loop=true -->",
        ].join("\n");
        const markers = parseAssessMarkers(body);
        expect(markers.phases).toEqual(["spec", "exec", "qa"]);
        expect(markers.action).toBe("PROCEED");
        expect(markers.qualityLoop).toBe(true);
      });

      it("should return empty object for no markers", () => {
        const markers = parseAssessMarkers("No markers here");
        expect(markers.phases).toBeUndefined();
        expect(markers.action).toBeUndefined();
        expect(markers.qualityLoop).toBeUndefined();
      });

      it("should ignore invalid action values", () => {
        const markers = parseAssessMarkers("<!-- assess:action=INVALID -->");
        expect(markers.action).toBeUndefined();
      });
    });

    describe("parseAssessWorkflow", () => {
      it("should parse full assess comment with PROCEED action", () => {
        const body = [
          "## Assess Analysis",
          "",
          "→ PROCEED — Issue is clear, codebase matches.",
          "",
          "Workflow: spec → exec → qa",
          "",
          "<!-- assess:phases=spec,exec,qa -->",
          "<!-- assess:action=PROCEED -->",
        ].join("\n");
        const result = parseAssessWorkflow(body);
        expect(result.phases).toEqual(["spec", "exec", "qa"]);
        expect(result.action).toBe("PROCEED");
      });

      it("should parse assess comment with CLOSE action", () => {
        const body = [
          "## Assess Analysis",
          "",
          "→ CLOSE — Resolved by PR #142.",
          "",
          "<!-- assess:action=CLOSE -->",
        ].join("\n");
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("CLOSE");
        expect(result.phases).toHaveLength(0);
      });

      it("should parse assess comment with REWRITE action", () => {
        const body =
          "## Assess Analysis\n\n→ REWRITE — PR too far behind.\n\n<!-- assess:action=REWRITE -->";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("REWRITE");
      });

      it("should parse assess comment with MERGE action", () => {
        const body =
          "## Assess Analysis\n\n→ MERGE — Overlaps with #198.\n\n<!-- assess:action=MERGE -->";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("MERGE");
      });

      it("should parse assess comment with CLARIFY action", () => {
        const body =
          "## Assess Analysis\n\n→ CLARIFY — Issue is too vague.\n\n<!-- assess:action=CLARIFY -->";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("CLARIFY");
      });

      it("should parse assess comment with PARK action", () => {
        const body =
          "## Assess Analysis\n\n→ PARK — Blocked on #175.\n\n<!-- assess:action=PARK -->";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("PARK");
      });

      it("should extract action from inline arrow notation when no HTML marker", () => {
        const body = "## Assess Analysis\n\n→ PROCEED — Ready for work.";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("PROCEED");
      });

      it("should prefer HTML marker action over inline action", () => {
        const body =
          "→ CLOSE — Looks resolved.\n\n<!-- assess:action=PROCEED -->";
        const result = parseAssessWorkflow(body);
        expect(result.action).toBe("PROCEED");
      });

      it("should extract issue numbers from header", () => {
        const body =
          "## Solve Workflow for Issues: #152, #153\n\nspec → exec → qa\n<!-- solve:phases=spec,exec,qa -->";
        const result = parseAssessWorkflow(body);
        expect(result.issueNumbers).toContain(152);
        expect(result.issueNumbers).toContain(153);
      });

      it("should prefer assess HTML markers over arrow notation for phases", () => {
        const body =
          "Workflow: spec → exec → test → qa\n<!-- assess:phases=exec,qa -->";
        const result = parseAssessWorkflow(body);
        expect(result.phases).toEqual(["exec", "qa"]);
      });

      it("should fall back to arrow notation when no HTML markers", () => {
        const body = "## Assess Analysis\n\nWorkflow: spec → exec → qa";
        const result = parseAssessWorkflow(body);
        expect(result.phases).toEqual(["spec", "exec", "qa"]);
      });

      it("should detect quality loop from text patterns", () => {
        const body =
          "## Assess Analysis\n\nQuality loop: auto-enable recommended\nWorkflow: spec → exec → qa";
        const result = parseAssessWorkflow(body);
        expect(result.qualityLoop).toBe(true);
      });

      it("should detect quality loop from --quality-loop flag mention", () => {
        const body =
          "## Assess Analysis\n\nRecommend --quality-loop for this issue\nWorkflow: spec → exec → qa";
        const result = parseAssessWorkflow(body);
        expect(result.qualityLoop).toBe(true);
      });
    });
  });

  // === FAILURE PATHS ===
  describe("error handling", () => {
    it("should handle malformed HTML markers gracefully", () => {
      // Markers with empty values should not throw
      expect(() => parseAssessMarkers("<!-- assess:phases= -->")).not.toThrow();
      const markers = parseAssessMarkers("<!-- assess:phases= -->");
      // Empty value produces array with empty strings filtered out
      expect(markers.phases).toBeDefined();
    });

    it("should handle empty comment body", () => {
      const result = parseAssessWorkflow("");
      expect(result.phases).toHaveLength(0);
      expect(result.qualityLoop).toBe(false);
      expect(result.issueNumbers).toHaveLength(0);
      expect(result.action).toBeUndefined();
    });

    it("should handle mixed assess and solve markers preferring assess", () => {
      const body = [
        "<!-- solve:phases=spec,exec -->",
        "<!-- solve:action=PROCEED -->",
        "<!-- assess:phases=exec,qa -->",
        "<!-- assess:action=CLOSE -->",
      ].join("\n");
      const result = parseAssessWorkflow(body);
      expect(result.phases).toEqual(["exec", "qa"]);
      expect(result.action).toBe("CLOSE");
    });
  });
});

// === AC-8: Phase signal system continues to work with assess output ===

describe("assess-to-phase-signal integration", () => {
  describe("AC-8: assessWorkflowToSignals", () => {
    it("should convert assess workflow to phase signals with source 'solve'", () => {
      const workflow: AssessWorkflowResult = {
        phases: ["spec", "exec", "qa"],
        qualityLoop: false,
        issueNumbers: [325],
        workflowString: "spec → exec → qa",
      };
      const signals = assessWorkflowToSignals(workflow);
      expect(signals).toHaveLength(3);
      expect(signals[0]).toEqual({
        phase: "spec",
        source: "solve",
        confidence: "high",
        reason: "Recommended by /assess command: spec → exec → qa",
      });
      expect(signals[1].phase).toBe("exec");
      expect(signals[2].phase).toBe("qa");
    });

    it("should include quality-loop signal when enabled", () => {
      const workflow: AssessWorkflowResult = {
        phases: ["spec", "exec"],
        qualityLoop: true,
        issueNumbers: [325],
      };
      const signals = assessWorkflowToSignals(workflow);
      expect(signals).toHaveLength(3);
      expect(signals[2]).toEqual({
        phase: "quality-loop",
        source: "solve",
        confidence: "high",
        reason: "Quality loop recommended by /assess command",
      });
    });

    it("should use phase name as fallback when no workflowString", () => {
      const workflow: AssessWorkflowResult = {
        phases: ["exec"],
        qualityLoop: false,
        issueNumbers: [],
      };
      const signals = assessWorkflowToSignals(workflow);
      expect(signals[0].reason).toBe("Recommended by /assess command: exec");
    });
  });

  // === FAILURE PATHS ===
  describe("error handling", () => {
    it("should produce empty signals for empty workflow", () => {
      const signals = assessWorkflowToSignals({
        phases: [],
        qualityLoop: false,
        issueNumbers: [],
      });
      expect(signals).toHaveLength(0);
    });
  });
});

// === AC-13: Backward-compat re-exports from solve-comment-parser.ts ===

describe("backward compatibility re-exports", () => {
  describe("AC-13: solve-comment-parser.ts re-exports", () => {
    it("should export isSolveComment as alias for isAssessComment", () => {
      expect(typeof isSolveComment).toBe("function");
      const body = "## Solve Workflow for Issues: 123\nspec → exec → qa";
      expect(isSolveComment(body)).toBe(true);
      // Also detects new format
      expect(isSolveComment("## Assess Analysis\n→ PROCEED")).toBe(true);
    });

    it("should export findSolveComment as alias for findAssessComment", () => {
      expect(typeof findSolveComment).toBe("function");
      const comments: IssueComment[] = [
        { body: "Regular" },
        { body: "## Solve Workflow for Issues: 123\nspec → exec" },
      ];
      const result = findSolveComment(comments);
      expect(result).not.toBeNull();
    });

    it("should export parseSolveWorkflow as alias for parseAssessWorkflow", () => {
      expect(typeof parseSolveWorkflow).toBe("function");
      const body =
        "## Solve Analysis\n\nspec → exec → qa\n<!-- solve:phases=spec,exec,qa -->";
      const result = parseSolveWorkflow(body);
      expect(result.phases).toEqual(["spec", "exec", "qa"]);
    });

    it("should export parseSolveMarkers as alias for parseAssessMarkers", () => {
      expect(typeof parseSolveMarkers).toBe("function");
      const markers = parseSolveMarkers("<!-- solve:phases=exec,qa -->");
      expect(markers.phases).toEqual(["exec", "qa"]);
    });

    it("should export solveWorkflowToSignals with /solve wording", () => {
      expect(typeof solveWorkflowToSignals).toBe("function");
      const workflow: AssessWorkflowResult = {
        phases: ["spec", "exec", "qa"],
        qualityLoop: false,
        issueNumbers: [123],
        workflowString: "spec → exec → qa",
      };
      const signals = solveWorkflowToSignals(workflow);
      expect(signals).toHaveLength(3);
      // Backward compat: uses "/solve" wording, not "/assess"
      expect(signals[0].reason).toBe(
        "Recommended by /solve command: spec → exec → qa",
      );
    });

    it("should export solveCoversIssue as alias for assessCoversIssue", () => {
      expect(typeof solveCoversIssue).toBe("function");
      const workflow: AssessWorkflowResult = {
        phases: [],
        qualityLoop: false,
        issueNumbers: [123, 456],
      };
      expect(solveCoversIssue(workflow, 123)).toBe(true);
      expect(solveCoversIssue(workflow, 789)).toBe(false);
    });

    it("should export SolveWorkflowResult as type alias", () => {
      // Type compatibility verified at compile time
      const result: SolveWorkflowResult = {
        phases: ["spec"],
        qualityLoop: false,
        issueNumbers: [],
      };
      expect(result.phases).toEqual(["spec"]);
    });

    it("should export SolveMarkers as type alias", () => {
      // Type compatibility verified at compile time
      const markers: SolveMarkers = {
        phases: ["exec"],
        action: "PROCEED",
      };
      expect(markers.phases).toEqual(["exec"]);
    });
  });
});

// === AC-6: /solve alias with deprecation notice ===

describe("solve alias deprecation", () => {
  describe("AC-6: parser handles both old and new formats", () => {
    it("should parse old solve format comments", () => {
      const body =
        "## Solve Analysis\n\n<!-- solve:phases=exec,qa -->\n<!-- solve:quality-loop=true -->";
      const result = parseAssessWorkflow(body);
      expect(result.phases).toEqual(["exec", "qa"]);
      expect(result.qualityLoop).toBe(true);
    });

    it("should parse new assess format comments", () => {
      const body = [
        "## Assess Analysis",
        "",
        "→ PROCEED — Ready for work.",
        "",
        "<!-- assess:phases=spec,exec,qa -->",
        "<!-- assess:action=PROCEED -->",
        "<!-- assess:quality-loop=true -->",
      ].join("\n");
      const result = parseAssessWorkflow(body);
      expect(result.phases).toEqual(["spec", "exec", "qa"]);
      expect(result.action).toBe("PROCEED");
      expect(result.qualityLoop).toBe(true);
    });
  });
});

// === assessCoversIssue ===

describe("assessCoversIssue", () => {
  it("should return true when issue is in the list", () => {
    const workflow: AssessWorkflowResult = {
      phases: [],
      qualityLoop: false,
      issueNumbers: [100, 200, 300],
    };
    expect(assessCoversIssue(workflow, 200)).toBe(true);
  });

  it("should return false when issue is not in the list", () => {
    const workflow: AssessWorkflowResult = {
      phases: [],
      qualityLoop: false,
      issueNumbers: [100, 200],
    };
    expect(assessCoversIssue(workflow, 999)).toBe(false);
  });
});
