/**
 * Test stubs for #914 AC-1 — `run.phases.<phase>.{model,effort}` settings.
 *
 * Generated by /testgen from the /spec comment on #914. `RunSettingsSchema`
 * does not parse `run.phases` yet (unknown keys are stripped by default zod
 * `.object()` behavior, so these assertions are RED until /exec adds the
 * `PhasePolicySchema` + `phases` field + `KNOWN_KEYS.run` entry + the
 * unknown-phase-name warning described in the spec). Do not "fix" these by
 * loosening the assertions — implement the feature.
 */

import { describe, it, expect } from "vitest";
import { RunSettingsSchema, validateSettings } from "./settings.js";

describe("#914 AC-1: run.phases settings", () => {
  it("round-trips a valid per-phase model/effort entry", () => {
    // Given: a settings object with run.phases.exec.effort = "medium"
    const input = {
      logJson: true,
      logPath: ".sequant/logs",
      autoDetectPhases: true,
      timeout: 1800,
      sequential: false,
      concurrency: 3,
      qualityLoop: false,
      maxIterations: 3,
      smartTests: true,
      mcp: true,
      retry: true,
      autoWaitMinutes: 0,
      staleBranchThreshold: 5,
      resolvedIssueTTL: 7,
      phases: {
        exec: { model: "sonnet", effort: "medium" },
      },
    };

    // When: parsed by RunSettingsSchema
    const result = RunSettingsSchema.parse(input);

    // Then: it round-trips
    expect((result as unknown as { phases?: unknown }).phases).toEqual({
      exec: { model: "sonnet", effort: "medium" },
    });
  });

  it("rejects an invalid effort value at parse time", () => {
    // Given: run.phases.spec.effort = "turbo" (not in the closed enum)
    const input = {
      phases: { spec: { effort: "turbo" } },
    };

    // When / Then: RunSettingsSchema.parse throws
    expect(() => RunSettingsSchema.parse(input)).toThrow();
  });

  it("yields undefined when run.phases is absent", () => {
    // Given: a settings object with no `phases` key
    const result = RunSettingsSchema.parse({});

    // Then: phases is undefined (zero-behavior-change default)
    expect((result as unknown as { phases?: unknown }).phases).toBeUndefined();
  });

  it("warns (non-fatal) on an unknown phase name, distinct from CLI fail-fast", () => {
    // Given: run.phases.bogus (not a real phase name)
    const raw = {
      run: {
        phases: { bogus: { model: "sonnet" } },
      },
    };

    // When: validateSettings walks the raw settings object
    const { warnings } = validateSettings(raw);

    // Then: a SettingsWarning is produced for the unknown phase name — this
    // must NOT throw (settings-side unknown phase = warning, not a crash;
    // that asymmetry vs. the CLI's fail-fast is intentional per the spec's
    // Open Question 3). Requires "run.phases" added to KNOWN_KEYS so the
    // recursive detectUnknownKeys() descends into it at all.
    expect(
      warnings.some((w) => w.path.includes("bogus")),
      "expected a warning naming the unknown phase 'bogus'",
    ).toBe(true);
  });
});
