name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: Estimate the complexity of fixing this bug (affects workflow selection)
      options:
        - simple
        - complex (quality loop)
        - refactor (quality loop)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area of the codebase does this affect?
      options:
        - ui
        - backend
        - cli
        - docs
      multiple: true
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details
      placeholder: |
        - OS: macOS 14.x
        - Node.js: 20.x
        - npm: 10.x
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots
      placeholder: Add any other context or screenshots about the bug here
    validations:
      required: false
