name: Documentation
description: Improve or add documentation
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the documentation change you want
      placeholder: This documentation update will...
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this?
      options:
        - README / Getting Started
        - API Documentation
        - Architecture / Design Docs
        - User Guide
        - Contributing Guidelines
        - Other
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: Estimate the complexity of this documentation task
      options:
        - simple
        - complex (quality loop)
        - refactor (quality loop)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area of the codebase does this document?
      options:
        - ui
        - backend
        - cli
        - docs
      multiple: true
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the specific criteria for this documentation to be considered complete
      placeholder: |
        - [ ] AC-1: ...
        - [ ] AC-2: ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or references
      placeholder: Add any other context about the documentation here
    validations:
      required: false
