name: Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what you want to happen
      placeholder: As a user, I want to...
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: Estimate the complexity of this feature (affects workflow selection)
      options:
        - simple
        - complex (quality loop)
        - refactor (quality loop)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area of the codebase does this affect?
      options:
        - ui
        - backend
        - cli
        - docs
      multiple: true
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the specific criteria for this feature to be considered complete
      placeholder: |
        - [ ] AC-1: ...
        - [ ] AC-2: ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: Add any other context or screenshots about the feature request here
    validations:
      required: false
