/**
 * Tests for report generation in upstream assessments
 */

import { describe, it, expect } from "vitest";
import {
  calculateSummary,
  generateAssessmentReport,
  generateFindingIssue,
  generateBatchedSummaryReport,
  generateLocalReport,
} from "../report.js";
import type {
  Finding,
  UpstreamAssessment,
  BatchedAssessment,
} from "../types.js";

describe("calculateSummary", () => {
  it("counts findings by category", () => {
    const findings: Finding[] = [
      {
        category: "breaking",
        title: "Breaking change",
        description: "Some breaking change",
        impact: "high",
        matchedKeywords: [],
        matchedPatterns: [],
        sequantFiles: [],
      },
      {
        category: "deprecation",
        title: "Deprecation",
        description: "Something deprecated",
        impact: "medium",
        matchedKeywords: [],
        matchedPatterns: [],
        sequantFiles: [],
      },
      {
        category: "new-tool",
        title: "New tool",
        description: "A new tool",
        impact: "low",
        matchedKeywords: [],
        matchedPatterns: [],
        sequantFiles: [],
      },
      {
        category: "no-action",
        title: "No action",
        description: "Nothing to do",
        impact: "none",
        matchedKeywords: [],
        matchedPatterns: [],
        sequantFiles: [],
      },
      {
        category: "no-action",
        title: "Another no action",
        description: "Also nothing to do",
        impact: "none",
        matchedKeywords: [],
        matchedPatterns: [],
        sequantFiles: [],
      },
    ];

    const summary = calculateSummary(findings);

    expect(summary.breakingChanges).toBe(1);
    expect(summary.deprecations).toBe(1);
    expect(summary.newTools).toBe(1);
    expect(summary.noAction).toBe(2);
    expect(summary.hookChanges).toBe(0);
    expect(summary.opportunities).toBe(0);
  });

  it("handles empty findings", () => {
    const summary = calculateSummary([]);

    expect(summary.breakingChanges).toBe(0);
    expect(summary.deprecations).toBe(0);
    expect(summary.newTools).toBe(0);
    expect(summary.noAction).toBe(0);
  });
});

describe("generateAssessmentReport", () => {
  const mockAssessment: UpstreamAssessment = {
    version: "v2.1.29",
    releaseDate: "2025-01-31",
    assessmentDate: "2025-01-31",
    previousVersion: "v2.1.28",
    findings: [
      {
        category: "breaking",
        title: "BREAKING: Removed old API",
        description: "Removed deprecated API endpoint",
        impact: "high",
        matchedKeywords: ["permission"],
        matchedPatterns: ["breaking"],
        sequantFiles: [".claude/settings.json"],
        issueNumber: 250,
      },
      {
        category: "new-tool",
        title: "New tool: ToolSearch",
        description: "Added ToolSearch for discovering MCP tools",
        impact: "low",
        matchedKeywords: ["tool", "MCP"],
        matchedPatterns: ["newTool"],
        sequantFiles: [],
        issueNumber: 251,
      },
    ],
    issuesCreated: [250, 251],
    summary: {
      breakingChanges: 1,
      deprecations: 0,
      newTools: 1,
      hookChanges: 0,
      opportunities: 0,
      noAction: 0,
    },
    dryRun: false,
  };

  it("includes version and dates in header", () => {
    const report = generateAssessmentReport(mockAssessment);

    expect(report).toContain("## Upstream: Claude Code v2.1.29 Assessment");
    expect(report).toContain("**Released:** 2025-01-31");
    expect(report).toContain("**Assessed:** 2025-01-31");
  });

  it("includes summary table", () => {
    const report = generateAssessmentReport(mockAssessment);

    expect(report).toContain("| Category | Count | Action Required |");
    expect(report).toContain("| Breaking Changes | 1 |");
    expect(report).toContain("| New Tools | 1 |");
  });

  it("includes breaking changes section", () => {
    const report = generateAssessmentReport(mockAssessment);

    expect(report).toContain("### Breaking Changes");
    expect(report).toContain("BREAKING: Removed old API");
    expect(report).toContain("**Issue created:** #250");
  });

  it("indicates dry run mode", () => {
    const dryRunAssessment = { ...mockAssessment, dryRun: true };
    const report = generateAssessmentReport(dryRunAssessment);

    expect(report).toContain("**Mode:** Dry Run");
  });

  it("includes footer", () => {
    const report = generateAssessmentReport(mockAssessment);

    expect(report).toContain("*Generated by /upstream skill*");
  });
});

describe("generateFindingIssue", () => {
  it("generates issue for breaking change", () => {
    const finding: Finding = {
      category: "breaking",
      title: "BREAKING: Removed old hook",
      description: "The old hook API was removed",
      impact: "high",
      matchedKeywords: ["hook"],
      matchedPatterns: ["breaking"],
      sequantFiles: ["src/hooks/pre-tool-hook.ts"],
    };

    const issue = generateFindingIssue(finding, "v2.1.29", 100);

    expect(issue.title).toContain("fix:");
    expect(issue.title).toContain("v2.1.29");
    expect(issue.body).toContain("**Upstream:** Claude Code v2.1.29");
    expect(issue.body).toContain("**Category:** Breaking Change");
    expect(issue.body).toContain("**Assessment:** #100");
    expect(issue.labels).toContain("upstream");
    expect(issue.labels).toContain("bug");
    expect(issue.labels).toContain("priority:high");
  });

  it("generates issue for deprecation", () => {
    const finding: Finding = {
      category: "deprecation",
      title: "Deprecated: oldFunction",
      description: "oldFunction is deprecated",
      impact: "medium",
      matchedKeywords: [],
      matchedPatterns: ["deprecation"],
      sequantFiles: [],
    };

    const issue = generateFindingIssue(finding, "v2.1.29");

    expect(issue.title).toContain("chore:");
    expect(issue.labels).toContain("upstream");
    expect(issue.labels).toContain("bug");
    expect(issue.labels).not.toContain("priority:high");
  });

  it("generates issue for new tool", () => {
    const finding: Finding = {
      category: "new-tool",
      title: "New tool: ToolSearch",
      description: "Added ToolSearch tool",
      impact: "low",
      matchedKeywords: ["tool"],
      matchedPatterns: ["newTool"],
      sequantFiles: [],
    };

    const issue = generateFindingIssue(finding, "v2.1.29");

    expect(issue.title).toContain("feat:");
    expect(issue.labels).toContain("upstream");
    expect(issue.labels).toContain("enhancement");
    expect(issue.labels).toContain("needs-triage");
  });

  it("includes affected files when present", () => {
    const finding: Finding = {
      category: "opportunity",
      title: "New feature",
      description: "Some new feature",
      impact: "low",
      matchedKeywords: [],
      matchedPatterns: [],
      sequantFiles: ["src/file1.ts", "src/file2.ts"],
    };

    const issue = generateFindingIssue(finding, "v2.1.29");

    expect(issue.body).toContain("### Affected Files");
    expect(issue.body).toContain("`src/file1.ts`");
    expect(issue.body).toContain("`src/file2.ts`");
  });
});

describe("generateBatchedSummaryReport", () => {
  const mockBatched: BatchedAssessment = {
    versions: ["v2.1.26", "v2.1.27", "v2.1.28"],
    sinceVersion: "v2.1.25",
    toVersion: "v2.1.28",
    summaryIssueNumber: 300,
    assessments: [
      {
        version: "v2.1.26",
        releaseDate: "2025-01-20",
        assessmentDate: "2025-01-31",
        previousVersion: "v2.1.25",
        findings: [],
        issuesCreated: [201],
        summary: {
          breakingChanges: 0,
          deprecations: 0,
          newTools: 1,
          hookChanges: 0,
          opportunities: 0,
          noAction: 2,
        },
        dryRun: false,
      },
      {
        version: "v2.1.27",
        releaseDate: "2025-01-25",
        assessmentDate: "2025-01-31",
        previousVersion: "v2.1.26",
        findings: [],
        issuesCreated: [202, 203],
        summary: {
          breakingChanges: 1,
          deprecations: 0,
          newTools: 0,
          hookChanges: 1,
          opportunities: 0,
          noAction: 3,
        },
        dryRun: false,
      },
    ],
  };

  it("includes version range in title", () => {
    const report = generateBatchedSummaryReport(mockBatched);

    expect(report).toContain("v2.1.25 → v2.1.28");
  });

  it("includes combined summary", () => {
    const report = generateBatchedSummaryReport(mockBatched);

    expect(report).toContain("### Combined Summary");
    expect(report).toContain("| Breaking Changes | 1 |");
    expect(report).toContain("| New Tools | 1 |");
  });

  it("includes per-version breakdown", () => {
    const report = generateBatchedSummaryReport(mockBatched);

    expect(report).toContain("### Per-Version Breakdown");
    expect(report).toContain("#### v2.1.26");
    expect(report).toContain("#### v2.1.27");
  });

  it("lists created issues", () => {
    const report = generateBatchedSummaryReport(mockBatched);

    expect(report).toContain("#201");
    expect(report).toContain("#202, #203");
  });
});

describe("generateLocalReport", () => {
  const mockAssessment: UpstreamAssessment = {
    version: "v2.1.29",
    releaseDate: "2025-01-31",
    assessmentDate: "2025-01-31",
    previousVersion: "v2.1.28",
    findings: [],
    issuesCreated: [],
    summary: {
      breakingChanges: 0,
      deprecations: 0,
      newTools: 0,
      hookChanges: 0,
      opportunities: 0,
      noAction: 0,
    },
    dryRun: false,
  };

  it("includes version in title", () => {
    const report = generateLocalReport(mockAssessment);

    expect(report).toContain("# Claude Code v2.1.29 Assessment");
  });

  it("includes assessment metadata", () => {
    const report = generateLocalReport(mockAssessment);

    expect(report).toContain("**Assessed:** 2025-01-31");
    expect(report).toContain("**Previous:** v2.1.28");
  });

  it("includes raw data section", () => {
    const report = generateLocalReport(mockAssessment);

    expect(report).toContain("## Raw Data");
    expect(report).toContain("```json");
    expect(report).toContain('"version": "v2.1.29"');
  });
});
