/**
 * Drift guard for plugin/memory/constitution.md (#1265).
 *
 * plugin/memory/constitution.md is a straight copy of
 * templates/memory/constitution.md, regenerated by scripts/sync-hooks.sh.
 * Before this test, editing templates/memory/constitution.md without
 * re-running the sync script left the shipped plugin copy stale with no
 * gate catching it — the QA review on #1265 found that appending to
 * plugin/memory/constitution.md directly left hook-sync, check-constitution-dod,
 * and lint:skill-sync all green, because none of them touch this file.
 *
 * Run `npm run sync:hooks` (scripts/sync-hooks.sh) to regenerate
 * plugin/memory/constitution.md after editing templates/memory/constitution.md.
 */

import * as fs from "fs";
import * as path from "path";
import { describe, expect, it } from "vitest";

const TEMPLATE_PATH = "templates/memory/constitution.md";
const PLUGIN_PATH = "plugin/memory/constitution.md";

describe("plugin/memory/constitution.md sync (#1265)", () => {
  const templateFull = path.join(process.cwd(), TEMPLATE_PATH);
  const pluginFull = path.join(process.cwd(), PLUGIN_PATH);

  it("plugin/memory/constitution.md is byte-identical to templates/memory/constitution.md", () => {
    expect(fs.existsSync(templateFull)).toBe(true);
    expect(fs.existsSync(pluginFull)).toBe(true);

    const templateBytes = fs.readFileSync(templateFull);
    const pluginBytes = fs.readFileSync(pluginFull);

    expect(pluginBytes.equals(templateBytes)).toBe(true);
  });
});
